

import type { Metadata } from "next";

import localFont from 'next/font/local';
import "../globals.css";
import Providers from "../providers";
import SlidesPage from "./slidesPage";

export const RubikLight = localFont({
  src: "../fonts/Rubik/static/Rubik-Light.ttf",
  variable: "--font-rubik-light",
});

export const RubikRegular = localFont({
  src: "../fonts/Rubik/static/Rubik-Regular.ttf",
  variable: "--font-rubik-regular",
});

export const RubikMedium = localFont({
  src: "../fonts/Rubik/static/Rubik-Medium.ttf",
  variable: "--font-rubik-medium",
});

export const RubikSemiBold = localFont({
  src: "../fonts/Rubik/static/Rubik-SemiBold.ttf",
  variable: "--font-rubik-semibold",
});

export const RubikBold = localFont({
  src: "../fonts/Rubik/static/Rubik-Bold.ttf",
  variable: "--font-rubik-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">

        <body className={`antialiased `}>

          {children}
          <SlidesPage />
        </body>

      </html>
    </Providers>
  );
}
